// deno-lint-ignore-file
import {
  quicktype,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
  InputData,
  JSONInput,
} from "npm:quicktype-core@23.2.6";
import $RefParser from "npm:@apidevtools/json-schema-ref-parser";


async function quicktypeJSONSchema(
  targetLanguage: any,
  typeName: string,
  jsonSchemaString: string,
  rendererOptions: Record<string, string> = {},
) {
  const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
  let flattenedSchema;
  try {
    const dereferencedSchema = await $RefParser.dereference(JSON.parse(jsonSchemaString), {
      dereference: { circular: "ignore" },
    });
    flattenedSchema = dereferencedSchema
  } catch (error) {
    console.error("Error parsing or dereferencing schema:", error);
    throw new Error("Invalid JSON schema or failed to resolve references");
  }
  await schemaInput.addSource({
    name: typeName,
    schema: JSON.stringify(flattenedSchema),
  });
  const inputData = new InputData();
  inputData.addInput(schemaInput);
  const renderOptions = {
    "just-types": "true",
    "no-extra-properties": "true", 
    "no-optional-null": "true",
    ...rendererOptions
  };
  return await quicktype({
    inputData,
    lang: targetLanguage,
    rendererOptions: renderOptions
  });
}

function extractRendererOptions(args: string[]): Record<string, string> {
  const options: Record<string, string> = {};
  for (const arg of args) {
    if (arg.startsWith("--build-flags=")) {
      const flags = arg.split("=")[1];
      for (const flag of flags.split(",")) {
        const trimmed = flag.trim();
        if (trimmed) {
          options[trimmed] = "true";
        }
      }
    }
  }
  return options;
}

async function main() {
    const [
    language = "typescript",
    schemaInput = "./schema.json",
    schemaName = "SchemaType",
    outputPath = "./output.txt",
    ...extraArgs
  ] = Deno.args;

  let text: string;
  const rendererOptions = extractRendererOptions(extraArgs);
  try {
    text = await Deno.readTextFile(schemaInput);
  } catch (_) {
    try {
      JSON.parse(schemaInput);
      text = schemaInput;
    } catch (err) {
      console.error(err);
      Deno.exit(1);
    }
  }
  const { lines } = await quicktypeJSONSchema(language, schemaName, text, rendererOptions);
  const output = lines.join("\n");
  const getCommentPrefix = (lang: string) => {
    switch (lang.toLowerCase()) {
      case 'python':
        return '#';
      default:
        return '//';
    }
  };
  const commentPrefix = getCommentPrefix(language);
  const currentDateTime = new Date().toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, ' UTC');
  const autoGeneratedComment = `${commentPrefix} This file is generated automatically by SuprSend based on available schema. DO NOT MODIFY IT.\n${commentPrefix} Generated on ${currentDateTime}\n\n`;
  let existingContent = "";
  try {
    existingContent = await Deno.readTextFile(outputPath);
  } catch(_) {}
  if (existingContent === "") {
    const finalOutput = autoGeneratedComment + output;
    await Deno.writeTextFile(outputPath, finalOutput);
  } else {
    let processedOutput = output;
    processedOutput = removeDuplicateImports(existingContent, output, language);
    const finalOutput = existingContent + "\n\n" + processedOutput;
    await Deno.writeTextFile(outputPath, finalOutput);
  }
}

function removeDuplicateImports(existingContent: string, newContent: string, language: string): string {
  const existingLines = existingContent.split('\n');
  const newLines = newContent.split('\n');
  const existingImports = new Map<string, Set<string>>();
  existingLines.forEach(line => {
    const trimmed = line.trim();
    if (isImportLine(trimmed, language)) {
      const parsed = parseImportLine(trimmed, language);
      if (parsed) {
        if (!existingImports.has(parsed.module)) {
          existingImports.set(parsed.module, new Set());
        }
        parsed.items.forEach(item => existingImports.get(parsed.module)!.add(item));
      }
    }
  });
  const filteredNewLines = newLines.filter(line => {
    const trimmed = line.trim();
    if (isImportLine(trimmed, language)) {
      const parsed = parseImportLine(trimmed, language);
      if (parsed) {
        const existingItems = existingImports.get(parsed.module) || new Set();
        const allItemsExist = parsed.items.every(item => existingItems.has(item));
        return !allItemsExist;
      }
    }
    return true;
  });

  return filteredNewLines.join('\n');
}

function parseImportLine(line: string, language: string): { module: string; items: string[] } | null {
  const lang = language.toLowerCase();
  switch (lang) {
    case 'python':
      const fromMatch = line.match(/^from\s+(\S+)\s+import\s+(.+)$/);
      if (fromMatch) {
        const module = fromMatch[1];
        const items = fromMatch[2].split(',').map(item => item.trim());
        return { module, items };
      }
      const importMatch = line.match(/^import\s+(\S+)$/);
      if (importMatch) {
        return { module: importMatch[1], items: [importMatch[1]] };
      }
      break;
    case 'typescript':
    case 'javascript':
      const namedMatch = line.match(/^import\s+\{([^}]+)\}\s+from\s+['"]([^'"]+)['"]/);
      if (namedMatch) {
        const items = namedMatch[1].split(',').map(item => item.trim());
        const module = namedMatch[2];
        return { module, items };
      }
      const starMatch = line.match(/^import\s+\*\s+as\s+(\S+)\s+from\s+['"]([^'"]+)['"]/);
      if (starMatch) {
        return { module: starMatch[2], items: [starMatch[1]] };
      }
      break;
  }
  return null;
}

function isImportLine(line: string, language: string): boolean {
  const lang = language.toLowerCase();
  switch (lang) {
    case 'python':
      return line.startsWith('from ') || line.startsWith('import ');
    case 'typescript':
    case 'javascript':
      return line.startsWith('import ') && (line.includes(' from ') || line.includes(';'));
    case 'java':
    case 'kotlin':
      return line.startsWith('import ') && line.endsWith(';');
    case 'go':
      return line.startsWith('import ') && (line.includes('"') || line.includes("'"));
    case 'dart':
      return line.startsWith('import ') && (line.includes("'") || line.includes('"'));
    case 'swift':
      return line.startsWith('import ');
    default:
      return false;
  }
}
main();